name: Create and push a Docker image

on:
  push:
    branches:
      - 'test'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    -
      run:
        echo ${{ secrets.DOCKER_REGISTRY }}
    -
      name: Checkout repository
      uses: actions/checkout@v4
    
    -
      name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    -
      name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/${{secrets.DOCKER_IMAGENAME}}
      
    -
      name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./catgpt/
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    

    

